extends SceneTree

const EXTENSIONS := ["gd", "tscn", "tres"]

const REPLACEMENTS := {
	"MissÃ£o": "Missão",
	"missÃ£o": "missão",
	"MissÃµes": "Missões",
	"missÃµes": "missões",
	"ConcluÃ­da": "Concluída",
	"concluÃ­da": "concluída",
	"ConcluÃ­do": "Concluído",
	"concluÃ­do": "concluído",
	"ApresentaÃ§Ã£o": "Apresentação",
	"apresentaÃ§Ã£o": "apresentação",
	"DireÃ§Ã£o": "Direção",
	"direÃ§Ã£o": "direção",
	"NotificaÃ§Ã£o": "Notificação",
	"notificaÃ§Ã£o": "notificação",
	"PosiÃ§Ã£o": "Posição",
	"posiÃ§Ã£o": "posição",
	"AÃ§Ã£o": "Ação",
	"aÃ§Ã£o": "ação",
	"TransiÃ§Ã£o": "Transição",
	"transiÃ§Ã£o": "transição",
	"AssociaÃ§Ã£o": "Associação",
	"associaÃ§Ã£o": "associação",
	"RegiÃ£o": "Região",
	"regiÃ£o": "região",
	"InformaÃ§Ã£o": "Informação",
	"informaÃ§Ã£o": "informação",
	"InformaÃ§Ãµes": "Informações",
	"informaÃ§Ãµes": "informações",
	"OpÃ§Ãµes": "Opções",
	"opÃ§Ãµes": "opções",
	"CriaÃ§Ã£o": "Criação",
	"criaÃ§Ã£o": "criação",
	"AtivaÃ§Ã£o": "Ativação",
	"ativaÃ§Ã£o": "ativação",
	"ConfiguraÃ§Ã£o": "Configuração",
	"configuraÃ§Ã£o": "configuração",
	"PontuaÃ§Ã£o": "Pontuação",
	"pontuaÃ§Ã£o": "pontuação",
	"AtualizaÃ§Ã£o": "Atualização",
	"atualizaÃ§Ã£o": "atualização",
	"ExploraÃ§Ã£o": "Exploração",
	"exploraÃ§Ã£o": "exploração",
	"ProgressÃ£o": "Progressão",
	"progressÃ£o": "progressão",
	"DistribuiÃ§Ã£o": "Distribuição",
	"distribuiÃ§Ã£o": "distribuição",
	"ProteÃ§Ã£o": "Proteção",
	"proteÃ§Ã£o": "proteção",
	"DuraÃ§Ã£o": "Duração",
	"duraÃ§Ã£o": "duração",
	"IntensificaÃ§Ã£o": "Intensificação",
	"intensificaÃ§Ã£o": "intensificação",
	"TransformaÃ§Ã£o": "Transformação",
	"transformaÃ§Ã£o": "transformação",
	"MaterializaÃ§Ã£o": "Materialização",
	"materializaÃ§Ã£o": "materialização",
	"EmissÃ£o": "Emissão",
	"emissÃ£o": "emissão",
	"ManipulaÃ§Ã£o": "Manipulação",
	"manipulaÃ§Ã£o": "manipulação",
	"EspecializaÃ§Ã£o": "Especialização",
	"especializaÃ§Ã£o": "especialização",
	"BÃºssola": "Bússola",
	"bÃºssola": "bússola",
	"HISTÃ“RIA": "HISTÓRIA",
	"HistÃ³ria": "História",
	"histÃ³ria": "história",
	"PRAÃ‡A": "PRAÇA",
	"PraÃ§a": "Praça",
	"praÃ§a": "praça",
	"CaÃ§adores": "Caçadores",
	"caÃ§adores": "caçadores",
	"CaÃ§ador": "Caçador",
	"caÃ§ador": "caçador",
	"CaÃ§a": "Caça",
	"caÃ§a": "caça",
	"ForÃ§a": "Força",
	"forÃ§a": "força",
	"FacÃ§Ã£o": "Facção",
	"facÃ§Ã£o": "facção",
	"FacÃ§Ãµes": "Facções",
	"facÃ§Ãµes": "facções",
	"TÃ©cnica": "Técnica",
	"tÃ©cnica": "técnica",
	"TÃ©cnicas": "Técnicas",
	"tÃ©cnicas": "técnicas",
	"ConexÃ£o": "Conexão",
	"conexÃ£o": "conexão",
	"EvoluÃ§Ã£o": "Evolução",
	"evoluÃ§Ã£o": "evolução",
	"AparÃªncia": "Aparência",
	"aparÃªncia": "aparência",
	"ExperiÃªncia": "Experiência",
	"experiÃªncia": "experiência",
	"PadrÃ£o": "Padrão",
	"padrÃ£o": "padrão",
	"CondiÃ§Ã£o": "Condição",
	"condiÃ§Ã£o": "condição",
	"CondiÃ§Ãµes": "Condições",
	"condiÃ§Ãµes": "condições",
	"RestriÃ§Ã£o": "Restrição",
	"restriÃ§Ã£o": "restrição",
	"RestriÃ§Ãµes": "Restrições",
	"restriÃ§Ãµes": "restrições",
	"NÃ­vel": "Nível",
	"nÃ­vel": "nível",
	"NÃ­veis": "Níveis",
	"nÃ­veis": "níveis",
	"Ã rea": "Área",
	"Ã¡rea": "área",
	"Ã reas": "Áreas",
	"Ã¡reas": "áreas",
	"AutomÃ¡tico": "Automático",
	"automÃ¡tico": "automático",
	"AutomÃ¡tica": "Automática",
	"automÃ¡tica": "automática",
	"BÃ¡sico": "Básico",
	"bÃ¡sico": "básico",
	"BÃ¡sica": "Básica",
	"bÃ¡sica": "básica",
	"CrÃ­tico": "Crítico",
	"crÃ­tico": "crítico",
	"MÃ¡ximo": "Máximo",
	"mÃ¡ximo": "máximo",
	"MÃ¡xima": "Máxima",
	"mÃ¡xima": "máxima",
	"MÃ­nimo": "Mínimo",
	"mÃ­nimo": "mínimo",
	"MÃ­nima": "Mínima",
	"mÃ­nima": "mínima",
	"Ãšnico": "Único",
	"Ãºnico": "único",
	"Ãšnica": "Única",
	"Ãºnica": "única",
	"VocÃª": "Você",
	"vocÃª": "você",
	"NÃ£o": "Não",
	"nÃ£o": "não",
	"EntÃ£o": "Então",
	"entÃ£o": "então",
	"EstÃ¡": "Está",
	"estÃ¡": "está",
	"EstÃ£o": "Estão",
	"estÃ£o": "estão",
	"SerÃ¡": "Será",
	"serÃ¡": "será",
	"SerÃ£o": "Serão",
	"serÃ£o": "serão",
	"TambÃ©m": "Também",
	"tambÃ©m": "também",
	"AlÃ©m": "Além",
	"alÃ©m": "além",
	"PorÃ©m": "Porém",
	"porÃ©m": "porém",
	"AtÃ©": "Até",
	"atÃ©": "até",
	"JÃ¡": "Já",
	"jÃ¡": "já",
	"LÃ¡": "Lá",
	"lÃ¡": "lá",
	"SÃ³": "Só",
	"sÃ³": "só",
	"NÃ³s": "Nós",
	"nÃ³s": "nós",
	"VÃ³s": "Vós",
	"vÃ³s": "vós",
	"Ãšltimo": "Último",
	"Ãºltimo": "último",
	"Ãšltima": "Última",
	"Ãºltima": "última",
	"PrÃ³ximo": "Próximo",
	"prÃ³ximo": "próximo",
	"PrÃ³xima": "Próxima",
	"prÃ³xima": "próxima",
	"DifÃ­cil": "Difícil",
	"difÃ­cil": "difícil",
	"FÃ¡cil": "Fácil",
	"fÃ¡cil": "fácil",
	"RÃ¡pido": "Rápido",
	"rÃ¡pido": "rápido",
	"RÃ¡pida": "Rápida",
	"rÃ¡pida": "rápida",
	"VitÃ³ria": "Vitória",
	"vitÃ³ria": "vitória",
	"MemÃ³ria": "Memória",
	"memÃ³ria": "memória",
	"SecretÃ¡ria": "Secretária",
	"secretÃ¡ria": "secretária",
	"InventÃ¡rio": "Inventário",
	"inventÃ¡rio": "inventário",
	"SessÃ£o": "Sessão",
	"sessÃ£o": "sessão",
	"VersÃ£o": "Versão",
	"versÃ£o": "versão",
	"DimensÃ£o": "Dimensão",
	"dimensÃ£o": "dimensão",
	"ConversÃ£o": "Conversão",
	"conversÃ£o": "conversão",
	"InvasÃ£o": "Invasão",
	"invasÃ£o": "invasão",
	"DecisÃ£o": "Decisão",
	"decisÃ£o": "decisão",
	"DivisÃ£o": "Divisão",
	"divisÃ£o": "divisão",
	"PortÃ£o": "Portão",
	"portÃ£o": "portão",
	"PortÃµes": "Portões",
	"portÃµes": "portões",
	"CapitÃ£o": "Capitão",
	"capitÃ£o": "capitão",
	"CidadÃ£o": "Cidadão",
	"cidadÃ£o": "cidadão",
	"CidadÃ£os": "Cidadãos",
	"cidadÃ£os": "cidadãos",
	"IrmÃ£o": "Irmão",
	"irmÃ£o": "irmão",
	"IrmÃ£os": "Irmãos",
	"irmÃ£os": "irmãos",
	"MÃ£o": "Mão",
	"mÃ£o": "mão",
	"MÃ£os": "Mãos",
	"mÃ£os": "mãos",
	"ChÃ£o": "Chão",
	"chÃ£o": "chão",
	"CoraÃ§Ã£o": "Coração",
	"coraÃ§Ã£o": "coração",
	"EspaÃ§o": "Espaço",
	"espaÃ§o": "espaço",
	"CabeÃ§a": "Cabeça",
	"cabeÃ§a": "cabeça",
	"GraÃ§a": "Graça",
	"graÃ§a": "graça",
	"PeÃ§a": "Peça",
	"peÃ§a": "peça",
	"BraÃ§o": "Braço",
	"braÃ§o": "braço",
	"ComeÃ§o": "Começo",
	"comeÃ§o": "começo",
	"ComeÃ§ar": "Começar",
	"comeÃ§ar": "começar",
	"AlcanÃ§ar": "Alcançar",
	"alcanÃ§ar": "alcançar",
	"LanÃ§ar": "Lançar",
	"lanÃ§ar": "lançar",
	"AvanÃ§ar": "Avançar",
	"avanÃ§ar": "avançar",
	"ForÃ§ar": "Forçar",
	"forÃ§ar": "forçar",
	"LÃ­quido": "Líquido",
	"lÃ­quido": "líquido",
	"SÃ³lido": "Sólido",
	"sÃ³lido": "sólido",
	"QuÃ­mica": "Química",
	"quÃ­mica": "química",
	"FÃ­sica": "Física",
	"fÃ­sica": "física",
	"FÃ­sico": "Físico",
	"fÃ­sico": "físico",
	"MÃ¡gico": "Mágico",
	"mÃ¡gico": "mágico",
	"MÃ¡gica": "Mágica",
	"mÃ¡gica": "mágica",
	"LÃ³gica": "Lógica",
	"lÃ³gica": "lógica",
	"Ãštil": "Útil",
	"Ãºtil": "útil",
	"InÃºtil": "Inútil",
	"inÃºtil": "inútil",
	"PrÃ©dio": "Prédio",
	"prÃ©dio": "prédio",
	"NegÃ³cio": "Negócio",
	"negÃ³cio": "negócio",
	"NegÃ³cios": "Negócios",
	"negÃ³cios": "negócios",
	"PrÃ³prio": "Próprio",
	"prÃ³prio": "próprio",
	"PrÃ³pria": "Própria",
	"prÃ³pria": "própria",
	"VÃ¡rio": "Vário",
	"vÃ¡rio": "vário",
	"VÃ¡rios": "Vários",
	"vÃ¡rios": "vários",
	"VÃ¡ria": "Vária",
	"vÃ¡ria": "vária",
	"VÃ¡rias": "Várias",
	"vÃ¡rias": "várias",
	"NecessÃ¡rio": "Necessário",
	"necessÃ¡rio": "necessário",
	"NecessÃ¡ria": "Necessária",
	"necessÃ¡ria": "necessária",
	"SecundÃ¡rio": "Secundário",
	"secundÃ¡rio": "secundário",
	"SecundÃ¡ria": "Secundária",
	"secundÃ¡ria": "secundária",
	"PrimÃ¡rio": "Primário",
	"primÃ¡rio": "primário",
	"PrimÃ¡ria": "Primária",
	"primÃ¡ria": "primária",
	"IntermediÃ¡rio": "Intermediário",
	"intermediÃ¡rio": "intermediário",
	"IntermediÃ¡ria": "Intermediária",
	"intermediÃ¡ria": "intermediária",
	"TemporÃ¡rio": "Temporário",
	"temporÃ¡rio": "temporário",
	"VoluntÃ¡rio": "Voluntário",
	"voluntÃ¡rio": "voluntário",
	"ContrÃ¡rio": "Contrário",
	"contrÃ¡rio": "contrário",
	"HorÃ¡rio": "Horário",
	"horÃ¡rio": "horário",
	"SalÃ¡rio": "Salário",
	"salÃ¡rio": "salário",
	"UsuÃ¡rio": "Usuário",
	"usuÃ¡rio": "usuário",
	"UsuÃ¡rios": "Usuários",
	"usuÃ¡rios": "usuários",
	"DiÃ¡rio": "Diário",
	"diÃ¡rio": "diário",
	"DiÃ¡logo": "Diálogo",
	"diÃ¡logo": "diálogo",
	"DiÃ¡logos": "Diálogos",
	"diÃ¡logos": "diálogos",
	"ðŸ ›ï¸": "🏛️",
	"ðŸ ›": "🏛️",
	"ðŸ“œ": "📜",
	"ðŸ ¹": "👑",
	"ðŸ—ºï¸": "🗺️",
	"ðŸ—º": "🗺️",
	"ðŸ’¬": "💬",
	"ðŸ‘‰": "👉",
	"âœ…": "✅",
	"âœ": "✓",
	"â¬œ": "⬜",
	"â›©ï¸": "⛩️",
	"â›©": "⛩️",
	"âš”ï¸": "⚔️",
	"âš”": "⚔️",
	"ðŸ‘": "👥",
	"âœ¨": "✨",
	"ðŸ’°": "💰",
	"ðŸ§©": "🧩",
	"ðŸ”¥": "🔥",
	"ðŸŒŸ": "🌟",
	"ðŸ’ª": "💪",
	"ðŸ›¡ï¸": "🛡️",
	"ðŸ›¡": "🛡️",
	"ðŸ’€": "💀",
	"âš ï¸": "⚠️",
	"âš ": "⚠️",
	"ðŸ †": "🏆",
	"ðŸŒŽ": "🌍",
	"ðŸŒ ": "🌐",
	"ðŸŽ¯": "🎯",
	"ðŸš€": "🚀",
	"ðŸ“š": "📖",
	"â ±ï¸": "⏱️",
	"â ±": "⏱️",
	"ðŸ”’": "🔒",
	"ðŸ”“": "🔓",
	"ðŸ—¡ï¸": "🗡️",
	"ðŸ—¡": "🗡️",
	"ðŸ ‰": "🐉",
	"ðŸ‘»": "👻",
	"ðŸ’¥": "💥",
	"ðŸ’¨": "💨",
	"â ¤ï¸": "❤️",
	"â ¤": "❤️",
	"âš¡": "⚡",
	"â­ ": "⭐",
	"ðŸ”°": "🔰",
	"ðŸŒŒ": "🌌",
	"ðŸ§¡": "🧡",
	"ðŸ’™": "💙",
	"ðŸ’œ": "💜",
	"ðŸ’š": "💚",
	"ðŸ‘ ï¸": "👁️",
	"ðŸ‘ ": "👁️",
	"ðŸ¥‹": "🥋",
	"ðŸŽ©": "🎩",
	"ðŸ“¦": "📦",
	"ðŸŽ ": "🎁",
	"ðŸŽµ": "🎵",
	"ðŸ”Š": "🔊",
	"ðŸ”‡": "🔇",
	"â€\"": "—",
	"â€œ": "“",
	"â€ ": "”",
	"â€˜": "‘",
	"â€™": "’",
	"â€¦": "…",
	"Ã¡": "á",
	"Ã©": "é",
	"Ã­": "í",
	"Ã³": "ó",
	"Ãº": "ú",
	"Ã£": "ã",
	"Ãµ": "õ",
	"Ã¢": "â",
	"Ãª": "ê",
	"Ã§": "ç",
	"Ã€": "À",
	"Ã‰": "É",
	"Ã ": "Á",
	"Ã”": "Ô",
	"Ãƒ": "Ã",
	"Ã‡": "Ç",
	"Ã•": "Õ",
	"Ãš": "Ú",
	"Ã“": "Ó"
}

func _init() -> void:
	print("==================================================")
	print("🧹 INICIANDO LIMPEZA GLOBAL DE MOJIBAKE & SINTAXE")
	print("==================================================")
	var arquivos: Array[String] = []
	_coletar_arquivos("res://", arquivos)
	print("Arquivos encontrados para varredura: %d" % arquivos.size())
	
	var modificados: int = 0
	for path in arquivos:
		if _processar_arquivo(path):
			modificados += 1
			print("  [CORRIGIDO] %s" % path)
			
	print("==================================================")
	print("✨ LIMPEZA CONCLUÍDA: %d arquivos restaurados com sucesso!" % modificados)
	print("==================================================")
	quit()


func _coletar_arquivos(dir_path: String, out_list: Array[String]) -> void:
	var dir := DirAccess.open(dir_path)
	if dir == null:
		return
	dir.list_dir_begin()
	var file_name = dir.get_next()
	while file_name != "":
		if file_name.begins_with("."):
			file_name = dir.get_next()
			continue
		var full_path = dir_path.path_join(file_name)
		if dir.current_is_dir():
			_coletar_arquivos(full_path, out_list)
		else:
			var ext = file_name.get_extension().to_lower()
			if ext in EXTENSIONS and not file_name.begins_with("fix_all_encodings"):
				out_list.append(full_path)
		file_name = dir.get_next()


func _processar_arquivo(path: String) -> bool:
	var file := FileAccess.open(path, FileAccess.READ)
	if file == null:
		return false
	var content = file.get_as_text()
	file.close()
	
	var original = content
	for k in REPLACEMENTS.keys():
		if k in content:
			content = content.replace(k, REPLACEMENTS[k])
			
	if content != original:
		var write_file := FileAccess.open(path, FileAccess.WRITE)
		if write_file != null:
			write_file.store_string(content)
			write_file.close()
			return true
	return false
